## YAML Template.
---
spring:
    application:
        name:
            BookEvaluationSpringBoot3
    sql:
        init:
            mode: always
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create


            
server:
    port:
        8081

#enable structured logging
logging:
    file:
        name: log.json
    structured:
        format:
            file: ecs

    threshold:
        console: TRACE
        file: DEBUG
        
---
spring:
    config:
        activate:
            on-profile: dev

management:
    endpoints:
        web:
            exposure:
                include:
                    shutdown, loggers
    endpoint:
        shutdown:
            access: unrestricted



---

#aop-profile

spring:
    config:
        activate:
            on-profile: aop-profile
            
com:
    rattencorp:
        aspects:
            AopConfigParameters:
                interceptorLevel: EXECPTIONS
        
        
---
#use h2-database

spring:
    config:
        activate:
            on-profile: h2-profile
    sql:
        init:
            platform: h2
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: me
        password: something
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
   
---
#mysql-profile

spring:
    config:
        activate:
            on-profile: mysql-profile
    sql:
        init:
            platform: mysql
    datasource:
        #TODO: replace with docker container
        url: jdbc:mysql://localhost:3306/firstjpa?createDatabaseIfNotExist=true
        driverClassName: com.mysql.cj.jdbc.Driver
        username: me
        password:
            